logo: # add logo name
title: StefanoPica
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/." # the subpath of your site, e.g. /blog
url: "https://73stefano.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Robot and Makers Blog # add banner title
banner-desc: Il mio Blog personale dove parlo di robot e altro # add banner description

# Author settings
author-pic: face1.jpg # your photo
author-name: Stefano Pica # your name
about-author:   Computer Science and Automation Engineering student,with the head in the Cloud,always passionate about the world of computing and cloud computing 
              # about author
email: stefano dot pica73 at gmail.com # your email
phone: 00000000 # your pnone number
website: https://github.com/73stefano # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier: # mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 9
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
